using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SpartaQuiz.Core
{
    class QuestionRepository
    {
        private readonly Random _random = new Random();

        private readonly List<QuestionItem> _questions; 

        public QuestionRepository()
        {
            _questions = GetQuestions().ToList();
        }

        public QuestionItem GetAQuestion()
        {
            return _questions.Skip(_random.Next(0, _questions.Count - 1)).First();
        }

        private IEnumerable<QuestionItem> GetQuestions()
        {
            yield return Create("“Skipper“ ist ein Fachausdruck im?", "Segeln");
            yield return Create("Ab wann wurde Aspirin als Medikament verkauft?", "1899");
            yield return Create("An welchem Fluss liegt Bordeaux?", "An der Garonne");
            yield return Create("An welchem Fluss liegt Hamburg?", "An der Elbe");
            yield return Create("An welchem Fluss liegt Kalkutta?", "Ganges");
            yield return Create("An welchem Fluss liegt London?", "An der Themse");
            yield return Create("An welchem Fluss liegt Wien?", "An der Donau");
            yield return Create("An welchem Meer liegt Helsinki?", "Am Finnischen Meerbusen (Ostsee)");
            yield return Create("An welchem Meer liegt Marseilles?", "Am Mittelländischen Meer ( Golfe de Lion)");
            yield return Create("An welchem Meer liegt Rio de Janeiro?", "Am Atlantischen Ozean");
            yield return Create("An welchem Meer liegt Schanghai?", "Am Chinesischen Meer");
            yield return Create("An welchem Meer liegt Scheveningen?", "An der Nordsee");
            yield return Create("An welchem Standort befand sich Griechenlands bedeutendstes Orakel?", "Delphi");
            yield return Create("An welchem Wochentag betrat zum ersten Mal ein Mensch den Mond?", "Montag");
            yield return Create("An welches Land wurde der Kriegsverbrecher Klaus Barbie ausgeliefert?", "Frankreich");
            yield return Create("Aphrodite ist die griechische Göttin ...", "...der Liebe und der Schönheit");
            yield return Create("Auf welche italienische Insel wurde Napoleon verbrannt?", "Elba");
            yield return Create("Auf welche japanischen Städte wurden Atombomben abgeworfen?", "Hiroschima und Nagasaki");
            yield return Create("Auf welchem Kontinent liegt Brasilien?", "Süd-Amerika");
            yield return Create("Auf welchem Kontinent liegt China?", "Asien");
            yield return Create("Auf welchem Kontinent liegt die Schweiz?", "Europa");
            yield return Create("Auf welchem Kontinent liegt Kongo?", "Afrika");
            yield return Create("Auf welcher Insel-Gruppe liegt Pearl Harbor?", "Hawaii");
            yield return Create("Auf welcher Mittelmeer-Insel spricht man Englisch?", "Malta");
            yield return Create("Auf wie viele Arbeitsstunden pro Woche einigte man sich nach dem Druckerstreick von 1984 in Deutschland?", "38.5 Stunden");
            yield return Create("Aus welchem Land stammt der Maler El Greco?", "Italien");
            yield return Create("Aus welchem Land stammt er Maler Vincent van Gogh?", "Niederlande");
            yield return Create("Aus welchem Material besteht ein Poloball?", "Holz");
            yield return Create("Aus welcher Bohne wird Fleischersatz gemacht?", "Soja");
            yield return Create("Aus welcher englischen Stadt stammen die Beatles?", "Liverpool");
            yield return Create("Aus welcher Substanz besteht das Körpergerüst von Käfern und Krebsen?", "Chitin");
            yield return Create("Bei welchem Spiel wird ein „Queue“ verwendet?", "Billard");
            yield return Create("Bei welchem Sport beträgt die Breite der Spielfläche 152.5cm?", "Tischtennis");
            yield return Create("Berlins Wappentier ist ein:", "Bär");
            yield return Create("Bob Beamon hält den Wetrekord im:", "Weitsprung");
            yield return Create("Bob Beamon setzt den Weltrekord des Jahrhunderts im Weitsprung", "1968");
            yield return Create("Chem. Formel von Sauerstoff?", "O2");
            yield return Create("Das weisse Hause ist der Wohnsitz des amerikanischen Präsidenten. In welcher Stadt liegt es?", "Washington");
            yield return Create("Der Sechstageskrieg im Nahen Osten tobt", "1967");
            yield return Create("Der zweite von Moart war ein Hit von Falco.", "Amadeus");
            yield return Create("Die Engländer Jane Torvill/Christopher Dean waren 4mal hintereinander Weltmeister im:?", "Eistanz");
            yield return Create("Die ersten compact discs kommen auf den Markt", "1981");
            yield return Create("Die ersten olympischen Winterspiele werden abgehalten", "1924");
            yield return Create("Die Hauptstadt von England?", "London");
            yield return Create("Die Hauptstadt von Russland?", "Moskau");
            yield return Create("Die Mauer in Berlin wird niedergerissen", "1989");
            yield return Create("Die nördlichen und südlichen Alpen bestehen aus:", "Kalk");
            yield return Create("Die Olympischen Spiele gehen diesen Sommer in Atlanta, USA vom Stapel", "1996");
            yield return Create("Die Sowjetunion sendet den ersten künstlichen Satelliten, Sputnik, ins All", "1957");
            yield return Create("Die Titanic geht unter", "1912");
            yield return Create("Durch welche Stadt fliesst der Tiber?", "Rom");
            yield return Create("Elvis Presleys erste <platte mit Heartbreak Hotel kommt heraus", "1956");
            yield return Create("Frankreich gewinnt die Fussballweltmeisterschaft auf eigenem Boden", "1998");
            yield return Create("Fremdwort für Festplatte?", "Harddisk");
            yield return Create("Für welches Instrument braucht der Musiker einen  “Besen“?", "Schlagzeug");
            yield return Create("Für welches Land spielte Pele?", "Brasilien");
            yield return Create("General Dwight Filley Davis spendete am 9. Februar 1900 einen Siegerpokal für welche Sportart?", "Tennis");
            yield return Create("Hasst Knoblauch, Sonnenlicht und hat kein Spiegelbild", "Vampir");
            yield return Create("Hollywood ist en Stadtteil von:?", "Los Angeles");
            yield return Create("In welchem Drama heisst es: Ein hohes Kleinod ist der gute Name?", "Mario Stuart");
            yield return Create("In welchem Jahr begann die Franz. Revolution?", "14. Juli 1789");
            yield return Create("In welchem Jahr wurde die Eidgenossenschaft gegründet?", "1291");
            yield return Create("In welchem Jahrhundert lebte Jean-Jacques Rousseau?", "18. Jh.");
            yield return Create("In welchem Land herrschte Idi  Amin?", "Syrien");
            yield return Create("In welchem Land kennt man teilweise noch heute die Witwenverbrennung?", "Indien");
            yield return Create("In welchem Land liegt Sao Paulo?", "Brasilien");
            yield return Create("In welchem Land liegt Vancouver", "Kanada");
            yield return Create("In welchem Monat darf man Edelweiss pflücken?", "Nie");
            yield return Create("In welchem Ta wurde 1922 das Grab des Pharaos Tut-ench-amun entdeckt?", "Tal der Könige");
            yield return Create("In welchen Monaten ist auf der südlichen Hemisphäre Winter?", "April – September");
            yield return Create("In welcher Einheit gibt man die Leistung eines elektr. Gerätes an?", "Watt");
            yield return Create("In welcher europäischen Stadt befindet sich der “Arc de Triumphe“?", "Paris");
            yield return Create("In welcher nordamerikanischen Stadt entstand der erste Wolkenkratzer?", "Chicago");
            yield return Create("In welcher Schlacht verlor Karl der Kühne das Leben?", "Bei Nancy");
            yield return Create("In welcher Sportart brauchte maqn einen Caddie?", "Crickel");
            yield return Create("In welcher Sportart wird der Ausdruck ,,Halsen“ gebraucht?", "Segeln");
            yield return Create("In welcher Stadt befindet sich der Tierpark Hellabrunn?", "In München");
            yield return Create("In welcher Stadt findet man eine Strasse mit den Namen “Die grosse Freiheit“", "Hamburg");
            yield return Create("In welcher Stadt gibt es Grachten?", "Amsterdam");
            yield return Create("In welcher Stadt ist das „Quartier Latin“?", "Ein Stadtteil von Paris, das Studentenviertel");
            yield return Create("In welcher Stadt kann man auf einem Flughafen namens “Orly“ landen?", "Paris");
            yield return Create("In welcher Stadt liess Richard Wagner ein Festspielhaus errichten?", "Bayreuth");
            yield return Create("In welcher Zeit spielt Markus Imhoofs Film „Das Boot ist voll“?", "Im 2. Weltkrieg");
            yield return Create("Indien wird selbständig", "1947");
            yield return Create("Japan attackiert Pearl Harbour", "1941");
            yield return Create("Joe DiMaggio war nicht nur der Ehemann von Marilyn Monroe, er war auch ein Spitzensportler. Als:", "Base-Ball-Spieler");
            yield return Create("Jose Napoleon Duarte ist der Präsident von:", "El Salvador");
            yield return Create("Karol Wojtyla, alias Johannes Paulus II wird Papst", "1978");
            yield return Create("Königin Victoria von Grossbritannien stirbt", "1901");
            yield return Create("Mischung zwischen Fussball, Reitsport und Golf?", "Polo");
            yield return Create("Mit welchem Auto verunfallte James Dean tödlich?", "Porsche");
            yield return Create("Mit welchem Filmstar ist die amerikanische Schauspielerin Mia Farrow gegenwärtig verheiratet?", "Woody Allen");
            yield return Create("Mit welchem Gerät kann man Bilder in den Computer einlesen?", "Scanner");
            yield return Create("Mit welchem Kriegsgegner nahmen die USA unter Bill Clinton widerdiplomatische Beziehungen auf?", "Vietnam");
            yield return Create("Mit welchem Land ist Grönland politisch assoziiert?", "Dänemark");
            yield return Create("Mit welchem Song hatte Nena einen grossen internationalen Erfolg?", "99 Luftballons");
            yield return Create("Mit welcher Filmrolle ist Pierre Brice berühmt geworden?", "Wennetou");
            yield return Create("Mit welcher Kunstrichtung bringt man Salvador Dali und Rene Magritte in Verbindung?", "Surrealismus");
            yield return Create("Mit wem schlossen Deutscchland und Italien 1940 einen Dreimächtepakt?", "Mit Japan");
            yield return Create("Nach welchem germanischen Volksstamm bezeichnet man noch heute sinnlose Beschädigungen?", "Vandalen");
            yield return Create("Nach welcher Konfession wurde Martin Luther getauft?", "Katholisch");
            yield return Create("Nach welcher Romanvorlage benannte sich ein berühmter Zauberkünstler?", "David Copperfield");
            yield return Create("Neil Armstrong geht am Mond spazieren", "1969");
            yield return Create("Nenne die Hauptstadt der Niederlande?", "Amsterdam");
            yield return Create("Nenne die Hauptstadt von Dänemark?", "Kopenhagen");
            yield return Create("Nenne die Hauptstadt von Polen?", "Warschau");
            yield return Create("Nenne die Hauptstadt von Schweiz?", "Bern");
            yield return Create("Nenne die Hauptstadt von Spanien?", "Madrid");
            yield return Create("Nenne die Hauptstadt von Tschechoslowakei?", "Prag");
            yield return Create("Nenne ein anderes Wort für Kältesteppen", "Tundra");
            yield return Create("Österreichs Thronfolger Franz Ferdinand wir in Sarajewo erschossen", "1914");
            yield return Create("Seit wann ungefähr gibt es Kaleidoskope?", "Anfang 19. Jahrhundert");
            yield return Create("Unter welchem Markenname ist Acetylsalicylsäure bekannt?", "Aspirin");
            yield return Create("Von welchem Land trennte sich Norwegen 1905?", "Schweden");
            yield return Create("Von welchem Tier wird Tamino in der “Zauberflöte“ bedroht?", "Schlane");
            yield return Create("Vor welchem Tieren fürchtete sich Napoleon?", "Katzen");
            yield return Create("Wann begann der Krieg zwischen Irak und Iran?", "29465");
            yield return Create("Wann entstand der Film „Fahrenheit 451“ von François Truffaut?", "1966");
            yield return Create("Wann entstand der Kanton Jura?", "1979");
            yield return Create("Wann explodierte die erste Wasserstoffbombe?", "1952");
            yield return Create("Wann fanden die ersten Olymp. Spiele der Moderne statt?", "1896");
            yield return Create("Wann gab es zum ersten mal seit 1928 keine Coca-Cola-Werbung an den Olympischen Spielen?", "1984");
            yield return Create("Wann gewann Hugo Koblet als erster Nichtitaliener den Giro d’Italia?", "1950");
            yield return Create("Wann hat die erste Fussball Weltmeisterschaft stattgefunden?", "1930");
            yield return Create("Wann marschierten sowjetische Truppen in der Tschechoslowokei ein?", "1968");
            yield return Create("Wann schloss Tudolf Brun das Bündnis mit den vier Waldstätten?", "1351");
            yield return Create("Wann starb Bismarck?", "1898");
            yield return Create("Wann starb der Psychiater C.G. Jung?", "1961");
            yield return Create("Wann starb Pablo Picasso?", "1967");
            yield return Create("Wann starb Richard Burton?", "1984");
            yield return Create("Wann starb Zarah Leander?", "1981");
            yield return Create("Wann startete der erste Zeppelin?", "1900");
            yield return Create("Wann trat das Schweizerische Zivilgesetzbuch in Kraft?", "1912");
            yield return Create("Wann trat die Schweiz dem Europarat bei?", "1963");
            yield return Create("Wann trat Ministerpräsident Menachem Begin zurück?", "1983");
            yield return Create("Wann traten die USA in den Ersten Weltkrieg ein?", "1917");
            yield return Create("Wann war der Aufstand der Pariser Kommune?", "1871");
            yield return Create("Wann war der letzte Bombenanschlag am Münchner Oktoberfest?", "1980");
            yield return Create("Wann war die erste Mondlandung?", "1969");
            yield return Create("Wann war die Schlacht von Morgarten?", "1315");
            yield return Create("Wann war die Schlacht von Waterloo?", "1815");
            yield return Create("Wann wurde Adolf Hitler geboren?", "1889");
            yield return Create("Wann wurde bei uns das Frauenstimmrecht eingeführt?", "1971");
            yield return Create("Wann wurde das Telefon erfunden?", "1861");
            yield return Create("Wann wurde der Cresta Run in St. Moritz eröffnet?", "1885");
            yield return Create("Wann wurde der Fünferbob von Viererbob abgelöst?", "1929");
            yield return Create("Wann wurde der Gotthardtunnel eingeweiht?", "1882");
            yield return Create("Wann wurde der Tonfilm erfunden?", "1928");
            yield return Create("Wann wurde die AHV eingeführt?", "1945");
            yield return Create("Wann wurde die Berliner Mauer niedergerissen?", "1989");
            yield return Create("Wann wurde die EWG gegründet?", "1957");
            yield return Create("Wann wurde die Fünfte Republik Frankreichs gegründet?", "1958");
            yield return Create("Wann wurde die Kapellbrücke in Luzern gebaut?", "1560-1600");
            yield return Create("Wann wurde die Sozialistgische Arbeiterpartei Deutschlands gegründet?", "1848");
            yield return Create("Wann wurde die UNO gegründet?", "1945");
            yield return Create("Wann wurde die zentrale Zürichbergbahn eröffnet?", "1895");
            yield return Create("Wann wurde Eisenhower Präsident der USA?", "1940");
            yield return Create("Wann wurde in der Schweiz das Metermass eingeführt?", "1874");
            yield return Create("Wann wurde in der UdSSR das erste Atomkraftwerk gebaut?", "1954");
            yield return Create("Wann wurde Ungarn von russischen Truppen besetzt?", "1956");
            yield return Create("Wann wurde Ungarn von russischen Truppen besetzt?", "1874");
            yield return Create("Wann wurde unsere Bundesverfassung zum erstenmal revidiert?", "1874");
            yield return Create("Warum ging es im alten Zürichkrieg?", "Um das Erbe von Toggenburg");
            yield return Create("Warum sind Eisberge so gefährlich?", "Weil nur 1/7  der Eismasse aus dem Meer ragt");
            yield return Create("Warum sind Eisberge so gefährlich?", "Weil der Grossteil unter das Wasseroberfläche ist und nicht sichtbar für die Schifffahrt.");
            yield return Create("Was bedeutet „ayatollah“?", "Gelehrter mit grossem religiösem Wissen");
            yield return Create("Was bedeutet „Mac“ am Anfang eines englischen Namens?", "Adelstitel");
            yield return Create("Was bedeutet ABS?", "Anti Blockier System");
            yield return Create("Was bedeutet das russische Wort Sputnik?", "Gefährte");
            yield return Create("Was bedeutet das Wort Blasphemie?", "Gotteslästerung");
            yield return Create("Was bedeutet der Titel „Duce“, den sich Mussolini zulegte?", "Führer");
            yield return Create("Was bedeutet die Abkürzung CH?", "Confoederatio Helvetica");
            yield return Create("Was bedeutet die Abkürzung ROM?", "Read Only Memory");
            yield return Create("Was bedeutet die Endung „-itis“ inmedizinischen Fachwörtern?", "Entzündung");
            yield return Create("Was bedeutet die Lehre Theologie?", "Die Lehre von Gott");
            yield return Create("Was bedeutet die Lehre von Agronomie?", "Lehre von Ackerbau");
            yield return Create("Was bedeutet die Lehre von Anatomie?", "Zerlegungslehre");
            yield return Create("Was bedeutet die Lehre von HYGIENE?", "Gesundheitslehre");
            yield return Create("Was bedeutet die Lehre von Mythologie?", "Lehre von den Gottheiten der Völker");
            yield return Create("Was bedeutet die Lehre von Zoologie?", "Tierkunde");
            yield return Create("Was bedeutet Extinktion?", "Die Abnahme der Lichtintensität in einer Substanz");
            yield return Create("Was beinhaltete der Marshall-Plan?", "Den Wiederaufbau Europas nach dem 2.Weltkrieg");
            yield return Create("Was bezeichnet die Apeninnenhalbinsel?", "Italien");
            yield return Create("Was bezeichnet die Apeninnenhalbinsel?", "Italien");
            yield return Create("Was braucht man um Arbeit zu verrichten?", "Energie");
            yield return Create("Was erfand Alfred Nobel, der Stifter des Friedensnobelpreises?", "Dynamit");
            yield return Create("Was frisst ein Mungo?", "Schlangen");
            yield return Create("Was für ein Landsman war der Lyriker Pablo Neruda?", "Chilene");
            yield return Create("Was für ein Landsmann ist Erich von Däniken?", "Deutscher");
            yield return Create("Was für ein Tier ist das Moschustier?", "Ein Hirsch");
            yield return Create("Was für ein Tier ist der Gänsesäger?", "Eine Grille");
            yield return Create("Was für ein Tier ist der Nimmersatt?", "Ein Storchenvogel");
            yield return Create("Was für ein Tier ist die Harpyie?", "Ein Raubvogel");
            yield return Create("Was gerät in heftige Bewegung, wenn der Mensch träumt?", "Die Augäpfel");
            yield return Create("Was haben die Hogwartsschüler laut der Schulhymne der Zauberschule im Kopf?", "Sie sind “leer, voll Luft und toter Fliegen“");
            yield return Create("Was heisst ,,Karate“ zu deutsch?", "Leere Hand");
            yield return Create("Was heisst „theater“ ursprünglich?", "Schauplatz");
            yield return Create("Was heisst „Video“ wörtlich?", "Ich sehe");
            yield return Create("Was heisst „Wodka“?", "Wässerchen");
            yield return Create("Was heisst der Name Felix wörtlich?", "Der Glückliche");
            yield return Create("Was ist Algebra?", "Die Lehre von den Gleichungen");
            yield return Create("Was ist bei einer Hepatitis (Gelbsucht) entzündet?", "Die Leber");
            yield return Create("Was ist Bernstein", "Versteinertes Baumharz");
            yield return Create("Was ist Chirologie?", "Die Handlesekunst");
            yield return Create("Was ist das grösste arktische Raubtier?", "Eisbär");
            yield return Create("Was ist Dekathlon?", "Zehnkampf");
            yield return Create("Was ist die einzige europäische Echse, die keine Beine hat", "Blindschleiche");
            yield return Create("Was ist die Lombardeirundfahrt?", "Radrennen");
            yield return Create("Was ist die Muttersprache von Albert Einstein?", "Deutsch");
            yield return Create("Was ist die Pole-Position?", "Bester Startplatz beim Automobielrennen");
            yield return Create("Was ist ein ,,Full House“?", "Ein Warenhaus");
            yield return Create("Was ist ein „Bonsai“?", "Japanischer Zwergbaum");
            yield return Create("Was ist ein „Pasch“?", "Zwei Würfel mit gleicher Augenzahl");
            yield return Create("Was ist ein Alkoven?", "Bettnische");
            yield return Create("Was ist ein Atheist?", "Ein Ungläubiger");
            yield return Create("Was ist ein Austernseitling?", "Speisepilz");
            yield return Create("Was ist ein Babauke?", "Ein Rohling");
            yield return Create("Was ist ein Epizentrum?", "Zentrum bei einem Erdbeben");
            yield return Create("Was ist ein Fön in der Natur?", "Ein warmer Fallwind");
            yield return Create("Was ist ein Koma?", "Tiefe Ohnmacht");
            yield return Create("Was ist ein Kuhpilz?", "Ein Klauhenpilz bei Kühen");
            yield return Create("Was ist ein Kurzkopf?", "Termitenfressender Frosch");
            yield return Create("Was ist ein Liebesapfel?", "Eine Tomate");
            yield return Create("Was ist ein Lori?", "Kleinpapagei");
            yield return Create("Was ist ein Omniphag?", "Allesfresser");
            yield return Create("Was ist ein Paso Doble?", "Span. Tanz");
            yield return Create("Was ist ein Ranger?", "Angehöriger einer US-Polizeitruppe");
            yield return Create("Was ist ein Ranger?", "Angehöriger einer US-Polizeitruppe");
            yield return Create("Was ist ein Seismograph?", "Gerät zum Aufzeichnen von Erdbebenwellen");
            yield return Create("Was ist ein Skeleton?", "Ein Rennschlitten");
            yield return Create("Was ist eine Fata Morgana?", "Luftspiegelung");
            yield return Create("Was ist eine Oligarchie?", "Herrschaft einer kleinen Gruppe");
            yield return Create("Was ist Halma?", "Ein Brettspiel, bei dem 2-4 Spieler die gegenüberliegende Ecke des Spielbrettes mit ihren Steinen zu besitzen trachten");
            yield return Create("Was ist in Fort Knox (Kentucky, USA) deponiert?", "Gold");
            yield return Create("Was ist Kernfusion?", "Die Verschmelzung von Atomkernen");
            yield return Create("Was ist passiert, wenn man sich eine Fraktur zugezogen hat?", "Knochenbruch");
            yield return Create("Was ist Patience?", "Ein Karten-Geduldspiel für einen Spieler");
            yield return Create("Was ist Roulette?", "Ein Glücksspiel mit einer Kugel auf einer drehbaren Scheibe mit schwarzen und roten numerierten Feldern");
            yield return Create("Was ist Stöchiometrie?", "Die Lehre von  der Zusammensetzung chemischer Verbindungen");
            yield return Create("Was ist Tetanus?", "Starrkrampf");
            yield return Create("Was ist Wolfram", "Ein Metall");
            yield return Create("Was ist, von Sibirien aus gesehen, auf der anderen Seite der Beringstrasse?", "Alaska");
            yield return Create("Was muss ein Fussballer tun, um einen Hattrick zu erzielen?", "Drei Tore hintereinander innerhalb einer Halbzeit");
            yield return Create("Was müssen Zahnärzte und Mathematiker besonders gut können?", "Wurzeln ziehen");
            yield return Create("Was nennt man „ The golden Gate“?", "Die Einfahrt in die Bucht von San Franzisko (Goldenes Tor)");
            yield return Create("Was schrieb Sigmund Freud 1930?", "Das Unbehangen in der Kultur");
            yield return Create("Was sind Aerobier?", "Mikroorganismen");
            yield return Create("Was sind Cherubim und Seraphim?", "Edelsteine");
            yield return Create("Was sind Kokken?", "Eine Bakterienart");
            yield return Create("Was sind Pheromone?", "Sexuallockstoffe");
            yield return Create("Was sind Steroide?", "Organische Verbindungen, z.B einige Hormone");
            yield return Create("Was symbolisieren die verschlungenen fünf Ringe der olympischen Fahne?", "Die fünf Kontinente");
            yield return Create("Was verbirgt sich hinter der Bezeichnung „Pizza Connection“?", "Heroinhändlerring");
            yield return Create("Was verstehen Filmemacher unter einem „remake“?", "Neuverfilmung eines verfilmten Stoffes");
            yield return Create("Was versteht man unter autonom?", "Selbständig");
            yield return Create("Was werden auf Longchamp ür Rennen ausgetragen?", "Pferderennen");
            yield return Create("Was wurde in den so genannten “Prohibitionsjahren“, in den USA verboten?", "Alkohol");
            yield return Create("Wegen was scheiterten Napoleon und Hitler in Russland gemeinsam?", "Am russischen Winter");
            yield return Create("Welche ansteckende Krankheit entvölkerte im Mittelalter halb Europa?", "Pest");
            yield return Create("Welche Bäume können mehr als 4000 Jahre alt werden?", "Mammutbäume");
            yield return Create("Welche Bäume werden am häufigsten vom Blitz getroffen?", "Eichen");
            yield return Create("Welche Berufssparte leistet den “Hippokratischen Eid“?", "Mediziner");
            yield return Create("Welche Dame holte sich 10mal hintereinander den Weltmeistertitel im Eiskunstlauf?", "Sonja Henie");
            yield return Create("Welche Delikatesse wird aus dem Rogen des Störs gewonnen?", "Kaviar");
            yield return Create("Welche deutsche Stadt wurde durch einen Rattenfänger bekannt?", "Hameln");
            yield return Create("Welche dieser Waffen ist die älteste?", "Holzkeule");
            yield return Create("Welche drei bedeutenden Kulturpflanzen kamen aus Amerika nach Europa?", "Kartoffeln, Mais, Tomaten");
            yield return Create("Welche Familie beherrschte während der Renaissance die Stadt Florenz", "Medici");
            yield return Create("Welche Farbe haben die Torstangen im Eishockey?", "Rot");
            yield return Create("Welche Farbe hat die Warnflagge bei Autorennen?", "Gelb");
            yield return Create("Welche Farbe ist in islamischen Ländern die Farbe der Trauer?", "Weiss");
            yield return Create("Welche Farben liegen im Regenbogen am weitesten auseinander?", "Rot und Violett");
            yield return Create("Welche Frau wird von Quasimodo verehrt?", "Esmeralda");
            yield return Create("Welche Frucht hat den grössten Nährwert?", "Die Avocado");
            yield return Create("Welche Funktion haben die Höcker eines Kamels?", "Fettspeicher");
            yield return Create("Welche Hochkultur lebte in den Anden?", "Inkas");
            yield return Create("Welche in der CH  beheimatete Schlange kann exzellent schwimmen?", "Ringelnatter");
            yield return Create("Welche Insel wird mit der Entstehung der Mafia in Zusammenhang gebracht?", "Sizilien");
            yield return Create("Welche Kinderbuchfigur wurde vom Schriftsteller Carlo Collodi Geschaffen?", "Pinoccio");
            yield return Create("Welche Kurorte in der Schweiz, in Deutschland und Österreich haben denselben Namen?", "Baden bei Zürich, Baden bei Wien und Baden-Baden im Schwarzwald");
            yield return Create("Welche Länder umschliessen den Bodensee?", "Österreich, Deutschland, (davon BadenWürttenberg, Bayern)");
            yield return Create("Welche Landsprache spricht man in der Republik San Marino?", "Italienisch");
            yield return Create("Welche Lebensrettende Medizin verdanken wir Alexander Flemming?", "Das Penicillin");
            yield return Create("Welche Linie hat kein Ende?", "Kreislinie");
            yield return Create("Welche Mannschaft siegte am häufigsten in der Deutschen Fussball-Bundesliga?", "Bayern München");
            yield return Create("Welche Mittelmeerinsel ist in eine griechischen und einen türkischen Teil gespaltet?", "Zypern");
            yield return Create("Welche Monate sind nach Menschen bennant?", "Januar und August");
            yield return Create("Welche Musikinstrumente tragen den Namen der Firma Steinway?", "Klaviere");
            yield return Create("Welche Naitonalität hat der Tenisspieler Vitas Gerulaitis?", "Amerikaner");
            yield return Create("Welche Nationalität hat der gegenwärtige Ehemann der Bhagwan-Abtrünnigen Sheela?", "Schweizer");
            yield return Create("Welche Nationalität hatte Maria Callas?", "Griechisch");
            yield return Create("Welche Oper wurde anlässlich der Eröffnung des Suezkanals komponiert?", "Aida");
            yield return Create("Welche Pflanze liefert den Grundstoff zur Schokoladenherstellung?", "Kakaobaum");
            yield return Create("Welche Pflanze wächst weltweit am schnellsten?", "Bambus");
            yield return Create("Welche Pilze lässt man von Schweinen suchen?", "Trüffel");
            yield return Create("Welche Säugetiere können fliegen?", "Fledermäuse");
            yield return Create("Welche Stadt bestand ursprünglich aus zwei Städten?", "Interlaken");
            yield return Create("Welche Stadt in den USA wurde 1906 durch ein Erdbeben fast vollständig zerstört?", "San Francisco");
            yield return Create("Welche Stadt wurde mit Hilfe eines hölzernen Pferdes erobert?", "Troja");
            yield return Create("Welche Tageszeit hat Gold im Mund?", "Morgenstund");
            yield return Create("Welche Tierart gab den Galapagos-Inseln ihren Namen?", "Schildkröte");
            yield return Create("Welche Tierhaut wurde früher als Schleifpapier benutzt?", "Haifischhaut");
            yield return Create("Welche US-Athletin nannte man „die Gazelle?“", "Wilma Rudolph");
            yield return Create("Welche Vögel legen ihre Eier in fremde Nester?", "Kuckuck");
            yield return Create("Welche Zivilisationen Südamerikas wurden durch die Spanier vernichten?", "Inkas");
            yield return Create("Welchem afrikanischen Raubtier fallen am meisten Menschen zum Opfer?", "Dem Krokodil");
            yield return Create("Welchem amerikanischen Konzern gehört die Organisation Weight Watchers?", "Heinz");
            yield return Create("Welchem Heiligen ist der Wiener Dom geweiht?", "Sankt Stefan");
            yield return Create("Welchem Vogel nennt man König der Lüfte?", "den Adler");
            yield return Create("Welchen Beruf hatte der Erfinder der Guillotine?", "Arzt");
            yield return Create("Welchen Club trainierte Helmut Benthaus, bevor er wieder zum FC Basel zurückkehrte?", "VfB Stuttgart");
            yield return Create("Welchen Krieg erlebte Kriminalschriftsteller Edgor Wallace an vorderster Front?", "Den Burenkrieg");
            yield return Create("Welchen Sport übte Ulrich Salchow aus?", "Eiskunstlauf");
            yield return Create("Welchen Teil Amerikas nennt man die amerikanische Riviera", "Die Küste Floridas in USA, am Golf von Mexiko");
            yield return Create("Welchen Titel trugen die Könige des alten Ägyptens?", "Pharao");
            yield return Create("Welcher “Unfall“ versetzte 1986 ganz Europa in Panik?", "Der GAU in Tschernobyl");
            yield return Create("Welcher Abenteuerroman beginnt mit dem Kapitel „Ein Greenhorn“?", "Winnetou");
            yield return Create("Welcher amerikanische Präsident billigte den Abwurf der Hiroshima-Bombe?", "Harry S. Truman");
            yield return Create("Welcher antike Feldherr starb, nachdem der den Grossteil der damals bekannten Welt erobert hatte?", "Alexander der Grosse");
            yield return Create("Welcher Bär aus Kinderbüchern bezeichnet sich selbst als einen “Bär von sehr geringem Verstand“?", "Winnie the Pooh");
            yield return Create("Welcher Boxer wurde erstmals durch einen unterklassigen Gegner besiegt?", "Muhammed Ali");
            yield return Create("Welcher Bruchteil des Eisbergs ragt ungefähr aus dem Wasser?", "41883");
            yield return Create("Welcher Bürgerrechtler motivierte seine Mitmenschen mit den Worten “...ich habe einen Traum..“?", "Martin Luther King");
            yield return Create("Welcher deutsche Boxer wurde erstmals Weltmeister im Schwergewicht?", "Max Schmeling");
            yield return Create("Welcher dieser drei italienischen Radhelden war Querfeldeinspezialist?", "Renato Longo");
            yield return Create("Welcher englische General schlug Napoleon bei Waterloo?", "Wellington");
            yield return Create("Welcher Entdecker lebte bis zu seinem Tode in dem Irrglauben, er wäre in Indien gewesen?", "Kolumbus");
            yield return Create("Welcher Gebirgszug trennt Europa von Asien?", "Ural");
            yield return Create("Welcher Hafen liegt an der Seine-Mündung?", "Le Havre");
            yield return Create("Welcher Held stürzte sich bei Sempach in die Speere?", "Winkelried");
            yield return Create("Welcher Kaiser wurde 1308 bei Königsfelden ermordet?", "Albrecht l.");
            yield return Create("Welcher Komponist war der Geliebte der Schriftstellerin George Sand?", "Frédéric Chopin");
            yield return Create("Welcher König von Frankreich hatte den Beinamen “Sonnenkönig“?", "Ludwig XIV");
            yield return Create("Welcher Kunsstil prägte den Ausdruck „Es ist verboten zu verbieten“?", "Surrealismus");
            yield return Create("Welcher Maler starb im März 1985?", "Marc Chagall");
            yield return Create("Welcher Mensch hat alle 10 Gebote gehalten?", "Moses");
            yield return Create("Welcher Monat hiess früher „Hornung“", "Februar");
            yield return Create("Welcher Papst erklärte sich für unfehlbar?", "Pius IX");
            yield return Create("Welcher Planet gilt als Herrscher der Sternzeichens Waage?", "Venus");
            yield return Create("Welcher Planet hat einen Ring?", "Saturn");
            yield return Create("Welcher Regisseur drehte ,,Der blaue Engel“?", "Ernst Lubitsch");
            yield return Create("Welcher Regisseur ist bekannt dafür, dass er in seinen eigenen Filmen jeweils selber kur auftritt?", "Alfred Hitchcock");
            yield return Create("Welcher Revolutionär wurde in der Badewanne ermordet?", "Marat");
            yield return Create("Welcher Riese der griechischen Sage trägt das Himmelsgewölbe auf den Schultern?", "Atlas");
            yield return Create("Welcher Roman von Thomas Mann wurde von Hans W. Geissendörfer verfilmt?", "Der Zauberberg");
            yield return Create("Welcher Schriftsteller war mit Marilyn Monroe verheiratet?", "Arthur Miller");
            yield return Create("Welcher Schweizer Politiker wurde im Herbst 1985 Ehrendoktor der Universität von Boston?", "Kurt Furgler");
            yield return Create("Welcher Schweizer Regisseur drehte den Film „Annebäbi Jowäger“?", "Franz Schnyder");
            yield return Create("Welcher Staatsmann starb am 4. Mai 1980?", "Josip Broz Tito");
            yield return Create("Welcher Star begann seine Weltkarriere mit dem Film „Der blaue Engel“?", "Marlene Dietrich");
            yield return Create("Welcher Stern kommt der Erde am nächsten?", "Die Sonne");
            yield return Create("Welcher Stil wurde Picasso zugeordnet?", "Surrealismus");
            yield return Create("Welcher südamerikanische Staat hat Portugiesisch als offizielle Landessprache?", "Brasilien");
            yield return Create("Welcher Tennisspieler gewann als jüngster Spieler in Wimbledon?", "Boris Becker");
            yield return Create("Welcher US-Präsident erhielt den Pulitzer-Preis?", "John F. Kennedy");
            yield return Create("Welcher Vogel hat die grösste Flügelspannweite?", "Der Albatros von vis zu 3.5m");
            yield return Create("Welcher Vogel kann 50km/h laufen?", "Strauss");
            yield return Create("Welcher Vogel kann im Sturzflug eine Geschwindigkeit von bis zu 360km/h erreichen?", "Der Wanderfalke");
            yield return Create("Welcher Wasserfall hat die grösste Sturzhöhe der Welt?", "Angel Falls (Venezuela)");
            yield return Create("Welcher Zwergstaat befindet sich zwischen Frankreich und Spanien?", "Andorra");
            yield return Create("Welches ägyptische Schreibmaterial gab dem Papier den Namen?", "Papyrus");
            yield return Create("Welches C befindet sich im Computer?", "Chip");
            yield return Create("Welches der folgenden Sprichwörter ist richtig?", "Das Kind mit dem Bad ausschütten");
            yield return Create("Welches deutschsprachige Volkslied wurde durch Elvis Presley ein Hit?", "Muss i den");
            yield return Create("Welches Eishockey-Team gewann an der Olympiade 1980 Gold?", "USA");
            yield return Create("Welches Fell brauchen wir zur Atmung?", "Zwerchfell");
            yield return Create("Welches Getreide wird am häufigsten zum Bierbrauen verwendet?", "Gerste");
            yield return Create("Welches Haustier wurde in Ägypten als Gott verehrt?", "Katze");
            yield return Create("Welches Instrument nennen Jazzmusiker ,,Kanne“?", "Saxophon");
            yield return Create("Welches Instrument spielte Glenn Miller?", "Posaune");
            yield return Create("Welches Instrument spielte Pablo Casals?", "Cello");
            yield return Create("Welches Instrument spielte Paul McCarney bei den Beatles?", "Bass");
            yield return Create("Welches ist das einzige Säugetier mit vier Knien?", "Elefant");
            yield return Create("Welches ist das internationale Zeichen der Schweiz im Segeln?", "Z");
            yield return Create("Welches ist das kleinste Säugetier Europas?", "Die Zwergfledermaus");
            yield return Create("Welches ist das nördlichste Land Afrikas?", "Tunesien");
            yield return Create("Welches ist das teuerste Küchengewürz?", "Safran");
            yield return Create("Welches ist der grösste europäische Binnenhafen?", "Duisburg am Rhein");
            yield return Create("Welches ist der höchste Alpenpass der Schweiz?", "Umbrailpass");
            yield return Create("Welches ist der längste Fluss Europas?", "Die Wolga?");
            yield return Create("Welches ist die älteste Porzellanmanufaktur Europas?", "Sèvres");
            yield return Create("Welches ist die älteste Religion der Welt?", "Judentum");
            yield return Create("Welches ist die grösste Insel im Mittelmeer?", "Sizilien");
            yield return Create("Welches ist die grösste Spinne der Welt?", "Die Vogelspinne");
            yield return Create("Welches ist die grösste Wüste Asiens?", "Die Wüste Gobi in der Mongolei");
            yield return Create("Welches ist die kürzeste Fährroute zwischen England und Frankreich?", "Dover-Calais");
            yield return Create("Welches ist die leichteste aller Holzarten?", "Balsaholz");
            yield return Create("Welches ist die letzte Disziplin beim Zehnkampf?", "1500m Lauf");
            yield return Create("Welches ist die Ursprüngliche Bedeutung des Wortes „Alarm“?", "Zu den Waffen");
            yield return Create("Welches ist Europas höchstes Bauwerk?", "Ein Radiomast bei Warschau");
            yield return Create("Welches ist flächenmässig der grösste Bezirk des Kantons Zürich?", "Winterthur");
            yield return Create("Welches kommunistische Land liegt den USA am nächsten?", "Die UdSSR");
            yield return Create("Welches Land besuchte der spanische König Juan Carlos im Mai 1984?", "Die Sowjetunion");
            yield return Create("Welches Land besuchte Margaret Thatcher im Februar 1984?", "Ungarn");
            yield return Create("Welches Land hat die grösste Waldfäche?", "Brasilien");
            yield return Create("Welches Land hat die längste Grenze zur Schweiz?", "Italien");
            yield return Create("Welches Land hiess früher Siam?", "Thailand");
            yield return Create("Welches Land hiess früher Siam?", "Thailand");
            yield return Create("Welches Land legalisierte schon 1935 den Schwangerschaftsabbruch?", "Island");
            yield return Create("Welches Land nennt man „Land der tausend Seen“?", "Finnland");
            yield return Create("Welches Land wählte im Mai 184 Leon Febres zum Präsidenten?", "Ecuador");
            yield return Create("Welches Land war im 2.Weltkrieg Schauplatz der Schlacht um El Alamein?", "Ägypten");
            yield return Create("Welches Land wurde 1984 von einer katastrophalen Hungersnot heimgesucht?", "Äthiopien");
            yield return Create("Welches Landtier kann am schnellsten laufen?", "Der Gepard");
            yield return Create("Welches Medikament gewinnt man aus Schimmelpilz?", "Penicillin");
            yield return Create("Welches Meer hat den höchsten Salzgehalt?", "Totes Meer");
            yield return Create("Welches Meer liegt 394 Meter unter dem Meeresspiegel?", "Das Tote Meer");
            yield return Create("Welches Musikinstrument spielt Woody Allen hervorragend?", "Saxophon");
            yield return Create("Welches Nahrungsmittel ist das meistangebaute und meistverzehrte der Welt?", "Weizen");
            yield return Create("Welches österreichische Bundesland hat Graz zur Hauptstadt?", "Steiermark");
            yield return Create("Welches russische Eislaufpaar war sechsmal hintereinander Weltmeister?", "Rodnina/Seizew");
            yield return Create("Welches Sportgerät wiegt nur 2.5 Gramm", "Ping Pong-Ball");
            yield return Create("Welches Tier hat Marilyn Monroe von Frank Sinatra geschenkt bekommen?", "Einen Pudel");
            yield return Create("Welches Tier war 1984 Organspender für das Herz eines Babies?", "Pavian");
            yield return Create("Welches Tier wird auch als “König der Tiere“ bezeichnet?", "Der Löwe");
            yield return Create("Welches war der letzte Film von Rainer Werner Fassbinder?", "Querelle");
            yield return Create("Welches waren Caesars Letzte Worte?", "Auch du, Brutus");
            yield return Create("Wen besiegte die Schweizer bei Morgarten?", "Die Hunnen");
            yield return Create("Wen liebte Don Quijote in seinen Tagträumen?", "Dulzinea");
            yield return Create("Wer begründete die chinesische Religion?", "Kung-fu-tse");
            yield return Create("Wer begründete die Relativitätstheorie?", "Einstein");
            yield return Create("Wer bekam den Nobelpreis zweimal?", "Marie Curie");
            yield return Create("Wer besiegelte die deusch-französische Freundschaft durch einen Vertrag?", "Erhard und de Gaulle");
            yield return Create("Wer bewies, dass das Licht eine begrenzte Geschwindigkeit hat?", "Ole Roemer");
            yield return Create("Wer entdeckte den Uranus?", "William Herschel");
            yield return Create("Wer entdeckte die elektromagnetischen Wellen?", "Heinrich Hertz");
            yield return Create("Wer erfand das Schaltgetriebe?", "Leonardo da Vinci");
            yield return Create("Wer erfand den Blitzableiter?", "Benjamin Franklin");
            yield return Create("Wer erfand den Indischen Untersee-Prinzen “Kaptäin Nemo“?", "Rembrandt");
            yield return Create("Wer erfand den Revolver?", "Samuel Colt");
            yield return Create("Wer erfand die Dampfmaschine?", "James Watt");
            yield return Create("Wer erfand die Dynamomaschine?", "Werner von Siemens");
            yield return Create("Wer erfand die Figur der Pippi Langstrumpf?", "Astrid Lindgren");
            yield return Create("Wer erfand die Glühbirne?", "T.A.Edison");
            yield return Create("Wer erfand die Kunst des Buchdrucks?", "Gutenberg");
            yield return Create("Wer erfand die  erste wirklich brauchbare Dampfmaschine", "James Watt");
            yield return Create("Wer führt in der ewigen Torschützenliste der deutschen Fussball-Bundesliga?", "Gerd Müller");
            yield return Create("Wer führte bei den Römern das Schaltjahr ein?", "Cäsar");
            yield return Create("Wer führte die Expedition, der zum ersten Mal die Welt umsegelte?", "Magellan");
            yield return Create("Wer gewann bei den Olympischen Winterspielen 1984 die Silbermedaille im Slalom?", "Steve Mohre");
            yield return Create("Wer gründete Bern?", "Die Zähringer");
            yield return Create("Wer hat „Oliver Twist“ geschrieben?", "Charles Dickens");
            yield return Create("Wer hat „Tod in Venedig“ geschrieben?", "Thomas Mann");
            yield return Create("Wer hat „Uli der Knecht“ geschrieben?", "Jeremias  Gotthelf");
            yield return Create("Wer hat „vom Winde verweht“ geschrieben?", "Mario Simmel");
            yield return Create("Wer hat Romulus und Remus gesäugt", "Ein Wolf");
            yield return Create("Wer hielt 1980 für 55 Minuten die Weltrekorde über 800m, 1000m, 1500m und 1 Meile", "Sebastian Coe");
            yield return Create("Wer komponierte den Hit „Strangers in the Night“?", "Bert Kaempfert");
            yield return Create("Wer komponierte die Oper „Tasca“?", "Puccini");
            yield return Create("Wer lief an der Olympiade 1980 die beste Eislaufkür der Damen?", "Denise Biellmann");
            yield return Create("Wer malte das Bild “Die sixtinische Madonna“?", "Raffael");
            yield return Create("Wer nahm Australien für die engl. Krone in Besitz?", "James Cock");
            yield return Create("Wer sagte : Je mehr Verbote es gibt im Reiche, desto ärmer wird das Volk?", "Laotse");
            yield return Create("Wer sagte: „Sie schlimmsten Fehler macht man in der Absicht, einen Fehler gutzumachen“", "Jean Paul");
            yield return Create("Wer sagte:“ Der Staat bin ich“?", "Ludwig XIV");
            yield return Create("Wer sandte 1983 während des Bürgerkrieges Truppen in den Tschad?", "Grossbritannien");
            yield return Create("Wer schloss 1904 die „Entente Cordiale“?", "Frankreich und England");
            yield return Create("Wer schrieb das Drehbuch zu Alfred Hitchcocks Film Strangers on a train?", "Raymond Chandler");
            yield return Create("Wer schrieb das Kinderbuch „Pippi Langstrumpf“?", "Astrid Lindgren");
            yield return Create("Wer schrieb den Roman, nach dem der Film “Jurassic Park“ gedreht wurde?", "Michael Crichton");
            yield return Create("Wer schrieb die „Love Story“?", "Erich Segal");
            yield return Create("Wer schrieb die erste eigentliche Detektivgeschichte?", "E. Wallance");
            yield return Create("Wer schrieb die Filmmusik für den James-Bond-Streifen „Im Angesicht des Todes“?", "Duran Duran");
            yield return Create("Wer schrieb die Kinderbücher “Das fliegende Klassenzimmer“ und “Emil und die Detektive“?", "Erich Kästner");
            yield return Create("Wer schrieb die unendliche Geschichte?", "Michel Ende");
            yield return Create("Wer schrieb unter dem Pseudonym Peter Panther?", "Ricarda Huch");
            yield return Create("Wer setzte zu Kriegszwecken eine Herde Elefanten ein und trieb sie über die Alpen?", "Konföderierte");
            yield return Create("Wer spielt die Tante Elise im “Teleboy“?", "Stephanie Glaser");
            yield return Create("Wer spielte der 1. James Bond?", "Sean Connery");
            yield return Create("Wer spielte die Hauptrolle in  der Fernsehserie über Richard Wagner?", "Johnny Weissmüller");
            yield return Create("Wer spielte die weibliche Hauptrolle in „Paris, Texas“?", "Nastassia Kinski");
            yield return Create("Wer sprach die berühmten Worte „Veni, vidi, vidi“?", "Cäsar");
            yield return Create("Wer starb laut griechischer Mythologie, weil ihm die Flügel schmolzen?", "Ikarus");
            yield return Create("Wer steckt hinter der schweizerischen Schoggitaler-Aktion?", "Der Schweizer Heimatschutz und der Bund für Naturschutz");
            yield return Create("Wer trat im Dezember 1984 aus der Unesco aus?", "Die USA");
            yield return Create("Wer verfilmte „French Lieutenant`s Woman“?", "Karel Reisz");
            yield return Create("Wer verfilmte „Ragtime“?", "Milos Forman");
            yield return Create("Wer verfilmte 1981 „ The Postman always rings twice“?", "Bob Rafelson");
            yield return Create("Wer verlonte „Das Wandern ist des Müllers Lust“?", "Franz Schubert");
            yield return Create("Wer vertonte den „Wilhelm Tell“?", "Rossini");
            yield return Create("Wer war 1979 Ski- Weltcupsieger in der Herrenabfahrt?", "Horti Weirather");
            yield return Create("Wer war 1981 Weltmeister im Eishockey?", "CSSR");
            yield return Create("Wer war am Ende der amerikanischen Wahlen 1984 der Gegner Ronald Reagans?", "Jesse Jackson");
            yield return Create("Wer war der Begründer der Psychoanalyse?", "Freud");
            yield return Create("Wer war der erste Amerikaner im All?", "Alan P. Shepard");
            yield return Create("Wer war der erste Präsident der USA?", "George Washington");
            yield return Create("Wer war der letzte deutsche Kaiser?", "Wilhelm ll.");
            yield return Create("Wer war Dirigent bei der Erstaufführung der Oper “Die Zauberflöte“?", "W. A. Mozart");
            yield return Create("Wer war europäischer Fussballer des Jahres 1983?", "Michel Platini");
            yield return Create("Wer war Fürst von Metternich?", "Leiter des Wiener Kongresses");
            yield return Create("Wer war in der Schweiz General während des Ersten Weltkrieges?", "Henri Dufour");
            yield return Create("Wer war mit 44 Jahren noch Box-Weltmeister seiner Klasse?", "Archie Moore");
            yield return Create("Wer war vor Bill Clinton Präsident der USA?", "George Bush");
            yield return Create("Wer wurde 1978 im eigenen Land Fussballweltmeister?", "Argentinien");
            yield return Create("Wer wurde fünfmal Formal-1 Weltmeister?", "Juan Manuel Fangio");
            yield return Create("Wessen Gott ist Merkur?", "Der Diebe und der Kaufleute");
            yield return Create("Weswegen sass der Marquis de Sade 27 Jahre im Kerker?", "Unzucht");
            yield return Create("Wie heissen die 5 Kontinente?", "Asien-Afrika-Europa-Amerkika-Australien");
            yield return Create("Wie heissen die Atmungsorgane der Fische?", "Kiemen");
            yield return Create("Wie heissen die Cowboys in Südamerika", "Gauchos");
            yield return Create("Wie heissen die flugunfähigen Vögel, die nur auf Neuseeland leben?", "Die Kiwis");
            yield return Create("Wie heissen die im Wasser lebenden, mit Kiemen atmenden Larven von Fröschen und Kröten?", "Kaulquappen");
            yield return Create("Wie heissen Die Ureinwohner Australiens?", "Aborigines");
            yield return Create("Wie heissen die Wasserfälle an der Grenze zwischen USA und Kanada?", "Niagara");
            yield return Create("Wie heissen die zerklüfteten Felsformationen, die man in Norwegen findet?", "Schären");
            yield return Create("Wie heisst das Autokennzeichen Spaniens?", "ESP");
            yield return Create("Wie heisst das Bauernmädchen in Mozarts „Don Giovanni“?", "Zerlina");
            yield return Create("Wie heisst das bekanteste Wahrzeichen Frankreichs?", "Eifelturm");
            yield return Create("Wie heisst das Fussballstadion von Real Madrid?", "Maracana");
            yield return Create("Wie heisst das geflügelte Pferd in der griechischen Mythologie?", "Pegasus");
            yield return Create("Wie heisst das griechische Pedant zum römischen Gott Neptun?", "Poseidon");
            yield return Create("Wie heisst das Hauptwerk von Karl Marx?", "Das Kapital");
            yield return Create("Wie heisst das Heiligtum des Islam in Mekko?", "Kaaba");
            yield return Create("Wie heisst das Hörspiel von Orson Welles, dessen Ausstrahlung in Amerika Panik auslöste?", "Krieg der Welten");
            yield return Create("Wie heisst das Künstlerviertel in New York?", "Greenwich Village");
            yield return Create("Wie heisst das rote Tuch beim Stierkampf?", "Kapa");
            yield return Create("Wie heisst das Südende der Feuerlandinsel?", "Kap Hoorn");
            yield return Create("Wie heisst der Affe, der mit Pippi Langstrumpf in der Villa Kunterbunt wohnt?", "Herr Nielson");
            yield return Create("Wie heisst der amerikanische Jasstrompeter, der mit dem Song “Wonderful World“ berühmt wurde?", "Louis Armstrong");
            yield return Create("Wie heisst der amtierende Präsident des IOC?", "Juan Antonio Samaranch");
            yield return Create("Wie heisst der aus Jamaika stammende Begründer der Reggae-Musik?", "Bob Marley");
            yield return Create("Wie heisst der australische Vogel Strauss?", "Emu");
            yield return Create("Wie heisst der bekannteste Park Londons?", "Hyde Park");
            yield return Create("Wie heisst der beste Freund von Fred Feuerstein?", "Barny Geröllheimer");
            yield return Create("Wie heisst der Erfinder der Glühbirne?", "Heinrich Goebel");
            yield return Create("Wie heisst der Federwechsel, der bei Vögeln jedes Jahr stattfindet?", "Mauer");
            yield return Create("Wie heisst der Genfer Flughafen?", "Henri Dunant");
            yield return Create("Wie heisst der Götterberg der Griechen?", "Olymp");
            yield return Create("Wie heisst der griechische Gott des Schlafes?", "Hypnos");
            yield return Create("Wie heisst der grosse Preis der Filmfestivals von Locarno?", "Goldener Leopard");
            yield return Create("Wie heisst der Gründer von Microsoft?", "Bill Gates");
            yield return Create("Wie heisst der heilige Berg in Tibet?", "Kailas");
            yield return Create("Wie heisst der heutige Vorgesetzte des im Aargauer Wanzenskandal in Verruf geratenen Polizeikommandanten Léon Borer?", "Victor Rickenbach");
            yield return Create("Wie heisst der höchste Berg Afrikas?", "Kilimandscharo");
            yield return Create("Wie heisst der höchste Berg Deutschlands?", "Zugspitze");
            yield return Create("Wie heisst der höchste Gipfel der Alpen?", "Mont Blanc");
            yield return Create("Wie heisst der höchste römische Gott?", "Jupiter");
            yield return Create("Wie heisst der in Japan äusserst angesehene Ringkamp-Sport?", "Sumo");
            yield return Create("Wie heisst der Keglergruss?", "Alle Neune");
            yield return Create("Wie heisst der Künstler, der im September 1985 den “Pont-Neuf“ verpackte?", "Christo");
            yield return Create("Wie heisst der Lac Léman auf deutsch?", "Genfersee");
            yield return Create("Wie heisst der längste Fluss Europas?", "Wolga");
            yield return Create("Wie heisst der Londoner Stadtteil, nach dem der Null-Meridian benannt ist?", "Greenwich");
            yield return Create("Wie heisst der Regisseur des Films 2010?", "Peter Hyams");
            yield return Create("Wie heisst der Regisseur des Films 2010?", "Peter Hyams");
            yield return Create("Wie heisst der Rennschlitten bei Hunde-Schlittenrennen?", "Pulka");
            yield return Create("Wie heisst der Schmuckstein, der in seinem Namen eine Schweizer Kantonshauptstadt verbringt?", "Bernstein");
            yield return Create("Wie heisst der Stadtteil von Paris, in dem die berühmten Kabaretts liegen?", "Montmartre");
            yield return Create("Wie heisst der weibliche Schweizer Leichtathletikstar der 70-er Jahre?", "Meta Antenen");
            yield return Create("Wie heisst der westlichste Punkt Englands?", "Lands End");
            yield return Create("Wie heisst die Amazone in einem Drama von Kleist?", "Penthesilea");
            yield return Create("Wie heisst die bayrische Landeshauptstadt und drittgrösste Stadt Deutschlands?", "München");
            yield return Create("Wie heisst die berühmte Reitschule in Wien?", "Spanische Hofreitschule");
            yield return Create("Wie heisst die berühmteste Sporthalle von New York?", "Madison Square Garden");
            yield return Create("Wie heisst die chem. Formel für Salzsäure?", "HCl");
            yield return Create("Wie heisst die Endstation der höchsten Zahnradbahn Europas?", "Wetterhorn");
            yield return Create("Wie heisst die Griechische Göttermutter?", "Hera");
            yield return Create("Wie heisst die grösste „wüste der Erde?", "Die Sahara in Nordafrika");
            yield return Create("Wie heisst die HS von Pakistan?", "Islamabad");
            yield return Create("Wie heisst die irische Fluggesellschaft?", "Air Lingus");
            yield return Create("Wie heisst die italienische Stadt in der Boote die meistgenutzten Verkehrsmittel sind?", "Venedig");
            yield return Create("Wie heisst die Jugendorganisation, die Hilfsbereitschaft und Pflichterfüllung als zentrale Aufgabe ansieht?", "Pfadfinder");
            yield return Create("Wie heisst die Krankheit anorexia nervosa auf Deutsch?", "Magersucht");
            yield return Create("Wie heisst die Landeswährung von Venezuela?", "Bolivar");
            yield return Create("Wie heisst die Lehre von dem Altertümern?", "Archäologie");
            yield return Create("Wie heisst die Lehre von dem Glauben?", "Dogmatik");
            yield return Create("Wie heisst die Lehre von dem Schall?", "Akustik");
            yield return Create("Wie heisst die Lehre von dem Wetter?", "Meteorologie");
            yield return Create("Wie heisst die Lehre von der Schiffahrt?", "Nautik");
            yield return Create("Wie heisst die Lehre von der Sternenkunde?", "Astronomie");
            yield return Create("Wie heisst die Lehre von der Zeit?", "Chronologie");
            yield return Create("Wie heisst die Popgruppe, in der Dieter Bohlen und Thomas Anders Mitte der 80er vereint waren?", "Modern Talking");
            yield return Create("Wie heisst die Regebogenhaut des Auges?", "Iris");
            yield return Create("Wie heisst die Stadt am Bosparus heute?", "Byzanz");
            yield return Create("Wie heisst die von einem Finnen lancierte neue Schrittechnik im Langlauf?", "Der Siitonenschritt");
            yield return Create("Wie heisst die weibliche Hauptrolle in My Fair Lady?", "Eliza Doolittle");
            yield return Create("Wie heisst die Zeit zwischen Ansteckung und Ausbruch einer Krankheit?", "Inkubationszeit");
            yield return Create("Wie heisst die zweitgrösste Insel im Mittelmeer?", "Sardinien");
            yield return Create("Wie heisst ein erstmals startendes Pferd im Rennsport?", "Dark Horse");
            yield return Create("Wie heisst ein Wald als Lawinenschutz?", "Bannwald");
            yield return Create("Wie heisst jede einzelne Spitze eines Hirschgeweihs?", "Spitz");
            yield return Create("Wie heisst Konstantinopel heute?", "Istanbul");
            yield return Create("Wie heisst Österreichs auflagenstärkste Tageszeitung?", "Kronenzeitung");
            yield return Create("Wie hiess das Mädchen, dem man 1984 ein Affenherz einpflanzte?", "Baby Fae");
            yield return Create("Wie hiess der erste amerik. Präsident?", "Washington");
            yield return Create("Wie hiess der erste Erdsatellit?", "Sputnik I");
            yield return Create("Wie hiess der erste Mensch im All?", "John H. Glenn");
            yield return Create("Wie hiess der erste römische Kaiser, der das Christentum als Religion erlaubte?", "Konstantin der Grosse");
            yield return Create("Wie hiess der letzte Coach der Schweizer Fussball-Nationalmannschaft vor Paul Wolfisberg?", "Léon Walker");
            yield return Create("Wie hiess der Mörder John F. Kennedys?", "Habib Oezel");
            yield return Create("Wie hiess der Reichsvogt Gessler mit Vornamen?", "Hermann");
            yield return Create("Wie hiess der Verfasser von Brehms Tierleben mit Vornamen?", "Alfred");
            yield return Create("Wie hiess die erste Bundesratskandidatin in der Schweiz?", "Lilian Uchtenhogen");
            yield return Create("Wie hiess die lanjährige Betreuerin der Kinder-Bastel-Stunde am Fernsehen DRS?", "Gerda Conzetti");
            yield return Create("Wie hiess die Mutter des Odipus?", "Jokaste");
            yield return Create("Wie hiess Othellos Ehefrau?", "Mirinda");
            yield return Create("Wie hoch ist das Matterhorn?", "4477 Meter");
            yield return Create("Wie hoch ist der höchste Berg der Erde?", "8840m");
            yield return Create("Wie hoch ist die Lichtgeschwindigkeit?", "300000 Kilometer pro Sekunde");
            yield return Create("Wie lang ist die Zunge einer Giraffe?", "40cm");
            yield return Create("Wie lang ist ein Tag auf dem Jupiter?", "9 Stunden 50 Minuten");
            yield return Create("Wie lang ist eine Marathonstrecke?", "Ca. 42km");
            yield return Create("Wie lange dauert ein Merkurjahr?", "88 Tage");
            yield return Create("Wie lange ist der Nil?", "6671 km");
            yield return Create("Wie lautet der medizinische Fachausdruck für Zahnfleischschwund?", "Parodontose");
            yield return Create("Wie nannte man den längsten in Europa stattfindenden Krieg?", "Den 30 jährigen Krieg");
            yield return Create("Wie nannte man Louis XIV", "Sonnenkönig");
            yield return Create("Wie nannte sich der oberste Rat im alten Rom?", "Senat");
            yield return Create("Wie nennt an die obere Begrenzung eines Fussballtores?", "Querlatte");
            yield return Create("Wie nennt der Volksmund den Thurgau?", "Mostindien");
            yield return Create("Wie nennt man Bäume, die in jahrelanger Arbeit klein gehalten werden?", "Bonsai");
            yield return Create("Wie nennt man beim Segeln die dem Wind zugekehrte Seite des Schiffes?", "Paralympics");
            yield return Create("Wie nennt man das Amphitheater in Rom?", "Kolosseum");
            yield return Create("Wie nennt man das gebogene Rohr unterhalb des Lavabos?", "Siphon");
            yield return Create("Wie nennt man das Gegengift, das man bei einem Schlangenbiss bekommt?", "Serum");
            yield return Create("Wie nennt man den Aufbau und die Gestaltung eines Tanzes?", "Choreographie");
            yield return Create("Wie nennt man den Lac Leman in der deutschen Schweiz?", "Genfersee");
            yield return Create("Wie nennt man den Schotten liebstes Musikinstrument?", "Dudelsack");
            yield return Create("Wie nennt man den unteren Abschluss der menschlichen Wirbelsäure?", "Steissbein");
            yield return Create("Wie nennt man die Paarungszeit bei Wölfen?", "Ranzzeit");
            yield return Create("Wie nennt man die Schleimhautentzündung von Magen und Darm?", "Gastritis");
            yield return Create("Wie nennt man ein Bild, das mit Wasserfarben auf Papier gemalt ist?", "Aquarell");
            yield return Create("Wie nennt man ein kastriertes männliches Pferd?", "Wallach");
            yield return Create("Wie nennt man eine Gruppe von Wölfen?", "Ein Rudel");
            yield return Create("Wie nennt man eine hohe Männersingstimme beim Singen?", "Tenor/Falsett");
            yield return Create("Wie nennt man eine Reitsport-Mannschaft?", "Crew");
            yield return Create("Wie nennt man einen jungen Hund?", "Welpe");
            yield return Create("Wie nennt man in der griechischen Mythologie die Fabelwesen mit Pferdeleibern und menschlichem Oberkörper?", "Kentauren(Zentauren)");
            yield return Create("Wie oft war New Yorks Bürgermeister Ed Koch ausgeliefert?", "Nie");
            yield return Create("Wie teuer war die Ablösesumme, die AC Neapel dem FC Barcelona für Diego Maradona bezahlte?", "17.8 Mio. Franken");
            yield return Create("Wie tief können Seehunde tauchen?", "Bis 400 Meter");
            yield return Create("Wie viel Alkohol im Blut ist tödlich?", "1-5%");
            yield return Create("Wie viel kann man beim Roulette mit einem Einsatz von 10 Franken maximal gewinnen?", "350 Franken");
            yield return Create("Wie viel macht tausend Gramm und 100m?", "1 Kilometer");
            yield return Create("Wie viel Prozent der Erdoberfläche entfallen auf Meer", "0,71");
            yield return Create("Wie viel Prozent pures Gold enthält 18-karätiges Gold?", "65");
            yield return Create("Wie viel Schokolade isst der Schweizer im Jahr?", "Ca. 10kg");
            yield return Create("Wie viel Spieler gibt es beim Rugby?", "30 Personen");
            yield return Create("Wie viele “Kegel“ werden beim Bowling aufgestellt?", "10");
            yield return Create("Wie viele Beine hat die Spinne?", "Acht");
            yield return Create("Wie viele Beine hat eine Spinne?", "8");
            yield return Create("Wie viele Brücken gibt es ungefähr in Venedig?", "400");
            yield return Create("Wie viele Felder hat ein Schachbrett?", "64");
            yield return Create("Wie viele Flügel hat eine Biene?", "8");
            yield return Create("Wie viele Karten braucht man zum Bridgespielen?", "52");
            yield return Create("Wie viele Länder grenzen an die Schweiz?", "6");
            yield return Create("Wie viele Nasenlöcher hat ein Potwal?", "Einst");
            yield return Create("Wie viele Oscars erhielt der Film „Amadeus“ 1985?", "5");
            yield return Create("Wie viele Saiten hat eine Mandoline?", "12");
            yield return Create("Wie viele Saturnringe gibt es?", "Ca. 100");
            yield return Create("Wie viele Seiten hat ein Pentagon", "5");
            yield return Create("Wie viele Steine hat ein Damespiel?", "24");
            yield return Create("Wie viele Sterne hat die amerik. Nationalflagge?", "50");
            yield return Create("Wie viele Sterne hat die amerikanische Flagge?", "50");
            yield return Create("Wie viele Zacken hat die Krone der Freiheitsstatue?", "Sieben");
            yield return Create("Wie viele Zahlen hat eine Roulette-Drehscheibe?", "37");
            yield return Create("Wie viele Zitzen hat das Euter einer Kuh?", "Vier");
            yield return Create("Wie war der Mädchenenname von Schillers  Frau?", "Charlotte von Kalb");
            yield return Create("Wie wird ein Segelwettbewerb genannt?", "Regatta");
            yield return Create("Wie wurde Adonis getötet?", "Von einem Eber");
            yield return Create("Wo befindet sich das Kap der Guten Hoffnung?", "In Südafrika, südlich Kapstadt");
            yield return Create("Wo befindet sich der Elbtunnel?", "In Hamburg zwischen St.Pauli und Steinwerder");
            yield return Create("Wo befindet sich der Erebus, der südlichste Vulkan der Erde?", "In der Antarktis");
            yield return Create("Wo befindet sich die Alhambra?", "Granada");
            yield return Create("Wo befindet sich die Blaue Moschee?", "Istanbul");
            yield return Create("Wo befindet sich die Zentrale der Interpol?", "Frankfurt");
            yield return Create("Wo entstanden im Januar 1984 Unruhen infolge Erhöhung des Brotpreises?", "Tunesien");
            yield return Create("Wo fand 1984 die Weltausstellung statt?", "In New Orleans");
            yield return Create("Wo fand die Olympiade im Jahr 2000 statt?", "Australien");
            yield return Create("Wo fanden die ersten Olympischen Spiele der Neuzeit statt?", "Athen");
            yield return Create("Wo fanden die Olympischen Winterspiele 1984 statt?", "Sarajevo");
            yield return Create("Wo fanden im Jahre 1996 die olymp. Sommerspiele statt?", "Atlanta");
            yield return Create("Wo findet das Oktoberfest statt?", "In München");
            yield return Create("Wo gab es die ersten Troubadoure?", "In Südfrankreich");
            yield return Create("Wo hat der internationale Gerichtshof seinen Sitz?", "Den Haag");
            yield return Create("Wo ist der Philosoph Theodor Adorno gestorben?", "In Visp");
            yield return Create("Wo ist die Bretagne?", "Eine westfranzösische Halbinsel mit hafenreicher Küste");
            yield return Create("Wo ist Leo Trotzki gestorben?", "Mexiko");
            yield return Create("Wo kamen die 41 Giftfässer her, die im Mai 1983 nach langer Suche wieder auftauchten?", "Aus Seveso");
            yield return Create("Wo leben die Wallonen?", "Belgien");
            yield return Create("Wo lebt der Dingo?", "austr. Wildhund");
            yield return Create("Wo lebte Pythagoras?", "Griechenland");
            yield return Create("Wo lebten die Inkas?", "Peru");
            yield return Create("Wo liegen Europas höchste Dünen?", "Portugal");
            yield return Create("Wo liegt Brooklyn?", "In New York (Stadtteil)");
            yield return Create("Wo liegt die Antarktis?", "Beim Südpol");
            yield return Create("Wo liegt Tabasco?", "Mexico");
            yield return Create("Wo sagte John F. Kennedy ,,Ich bin ein Berliner“?", "Im Radiostudio");
            yield return Create("Wo starb Che Guevara?", "In Argentinien");
            yield return Create("Wo steht die Stephanskirche?", "In Wien");
            yield return Create("Wo steht Michelangelos David?", "In Florenz");
            yield return Create("Wo trägt man einen Sombrero?", "Mexiko");
            yield return Create("Wo trugen die Fussballer die letzte Weltmeisterschaft des Jahrtausends aus?", "Frankreich");
            yield return Create("Wo war der  Grieche Achilles verletzbar?", "An der Ferse");
            yield return Create("Wo weilte Michail Gorbatschow im Dezember 1984 auf Staatsbesuch?", "London");
            yield return Create("Wo wohnen die „Schlümpfe“?", "In Schlumpfhausen");
            yield return Create("Wo wuirde in der Schweiz die letzte Hexe verbrannt?", "Luzern");
            yield return Create("Wo wurde am 18.4.1983 ein Anschlag auf die amerikanische Botschaft verübt?", "In Beirut");
            yield return Create("Wo wurde die erste Schweizer Radiostation eingerichtet?", "Beromünster");
            yield return Create("Wo wurde die Schauspielerin Anna Magnani geboren?", "Ägypten");
            yield return Create("Wo wurde dieses Jahr erstmals Polo auf Eis gespielt?", "St. Moritz");
            yield return Create("Wo wurde Napoleon geboren?", "Korsika");
            yield return Create("Wo wurde Richard Wagner geboren?", "Leipzig");
            yield return Create("Wo wurde William Shakespeare geboren?", "Stratford on Avon");
            yield return Create("Wofür streikten die Drucker in der BRD im April 1984", "Für die 35-Stunden-Woche");
            yield return Create("Woher kam die Miss Europa 1984?", "Aus Belgien");
            yield return Create("Woher kommt der Tilsiterkäse?", "Elsass");
            yield return Create("Woher stammt der Ausdruck Doping?", "Vom Zuluausdruck Doop (berauschender Schnaps)");
            yield return Create("Woher stammt die berühmte Goldmaske des Agamemnan?", "Aus Mykene");
            yield return Create("Woher stammt die Siamkatze?", "Thailand");
            yield return Create("Womit betreibt man die Sportart Keirin?", "Langlaufskis");
            yield return Create("Womit hob E. Spelterini 1898 erstmals ab?", "Freiluftballon");
            yield return Create("Womit ist John D. Rockefeller reich geworden?", "Öl");
            yield return Create("Womit sind ungefähr 70 Prozent der Erdoberfläche bedeckt?", "Wasser");
            yield return Create("Wonach schmeckt Grand Marnier?", "Nach Zitronen");
            yield return Create("Woraus bestehen die Höcker der Kamele?", "Fettgewebe");
            yield return Create("Woraus entsteht Tofu?", "Sojabohnen");
            yield return Create("Woraus macht man Sake?", "Reis");
            yield return Create("Woraus wurde ursprünglich die Farbe Purpur hergestellt?", "Aus Beeren");
            yield return Create("Worin badet Dagobert Duck von Zeit zu Zeit?", "In Geld");
            yield return Create("Ws ist ein Toxikologe?", "Ein Forscher, der Gifte untersucht");
            yield return Create("Zu welchem Land gehört Luxor?", "Ägypten");
            yield return Create("Zu welchem Staat gehören die Azoren?", "Portugal");
            yield return Create("Zu welchen zwei Ländern gehören die Jungferninseln?", "GB und USA");
            yield return Create("Zu welcher Boxerkategorie zählte Muhammad Ali?", "Schwergewicht");
            yield return Create("Zu welcher Gattung gehören die Salamander?", "Amphibien");
            yield return Create("Zu welcher Gattung gehört der Koalabär?", "Beuteltiere");
            yield return Create("Zu welcher Hunderasse gehört der beliebte Fernsehhund “Lassie“?", "Collie");
            yield return Create("Zu welcher Sportart gehört der Begriff „Damengambil“?", "Schach");

        }

        private QuestionItem Create(string question, string answer)
        {
            var q = new QuestionItem();
            q.QuestionGuid = Guid.NewGuid();

            q.RightAnswer = _random.Next(0, 4);

            q.Question = question;

            q.Answers[0] = "falsch";
            q.Answers[1] = "falsch";
            q.Answers[2] = "falsch";
            q.Answers[3] = "falsch";

            q.Answers[q.RightAnswer] = answer;

            return q;
        }
    }
}
